apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-k3s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-k3s
  template:
    metadata:
      labels:
        app: nginx-k3s
    spec:
      containers:
      - name: nginx
        image: localhost:5000/test-k3s-nginx
        ports:
        - containerPort: 80

